# Model arguments
model_name_or_path: google/gemma-2-9b
# tokenizer_name_or_path: PolyAgent/gemma-ua-20k-tokenizer
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
    PolyAgent/ubertext_full: 1.0
    # PolyAgent/wiki_uk_en_parallel: 1.0
    # PolyAgent/fineweb-edu-5B: 1.0
    # PolyAgent/textbooks: 1.0
dataset_splits:
    - train
    - test
text_column: text
# dataset_configs:
#   - tiny
preprocessing_num_workers: 256

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 300
# gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
    use_reentrant: False
hub_model_id: antonpolishko/gemma-2-9b-overfit-ua
hub_strategy: checkpoint
learning_rate: 0.2e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1 # 1212 5.71s/it
num_train_epochs: 3
output_dir: /home/openbabylon/ckpts/gemma-2-9b-overfit-ua
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 8
push_to_hub: true
remove_unused_columns: true
report_to:
    - wandb
    - tensorboard
save_strategy: "epoch"
save_steps: 300
save_total_limit: 15
seed: 42
warmup_ratio: 0.001
